name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore ./RomanConverter.sln

      - name: Build the project
        run: dotnet build ./RomanConverter.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ./RomanConverterTest/RomanConverterTest.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./RomanConverterTest/TestResults.trx

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Build the project
        run: dotnet build ./RomanConverter.sln --configuration Release

      - name: Create the package
        run: dotnet pack ./RomanConverter/RomanConverter.csproj --configuration Release

      - name: Publish the package
        run: dotnet nuget push ./RomanConverter/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}